server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: cambio-service
  datasource:
    url: jdbc:h2:mem:testdb
    username: user
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
management:
  tracing:
    sampling:
      probability: 1.0